/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.traders.app;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.traders.utilidades.CapturandoHora;
import java.awt.Color;
import java.awt.Font;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.function.Function;
import org.bson.Document;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author Windows 7
 */
public class CadastroOCR extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public CadastroOCR() {
        initComponents();
        
        
    }
    
    
            MongoClient mongoCliente = new MongoClient();

            MongoDatabase database = mongoCliente.getDatabase("dbTraders");

            MongoCollection<Document> collection = database.getCollection("ocorrencias");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastro = new javax.swing.JButton();
        statusOCR = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fundo30 = new javax.swing.JCheckBox();
        topo30 = new javax.swing.JCheckBox();
        fundoDiario = new javax.swing.JCheckBox();
        topoDiario = new javax.swing.JCheckBox();
        fundo30_diario = new javax.swing.JCheckBox();
        topo30_diario = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sim_ponto = new javax.swing.JCheckBox();
        nao_ponto = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sim_ranger = new javax.swing.JCheckBox();
        nao_ranger = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sim_acertou = new javax.swing.JCheckBox();
        nao_acertou = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Ocorrencias Automatico");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastro.setText("Cadastro de Ocorrencia");
        cadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        statusOCR.setText("status da ocorrencia");

        date.setText("Data");

        labelHora.setText("00:00:00");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome da Ocorrencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        fundo30.setText("fundo30");
        fundo30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundo30ActionPerformed(evt);
            }
        });

        topo30.setText("topo30");
        topo30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topo30ActionPerformed(evt);
            }
        });

        fundoDiario.setText("fundo diario");
        fundoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundoDiarioActionPerformed(evt);
            }
        });

        topoDiario.setText("topo diario");
        topoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topoDiarioActionPerformed(evt);
            }
        });

        fundo30_diario.setText("fundo30 - diario");
        fundo30_diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundo30_diarioActionPerformed(evt);
            }
        });

        topo30_diario.setText("topo30 - diario");
        topo30_diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topo30_diarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fundo30)
                    .addComponent(topo30)
                    .addComponent(fundoDiario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topo30_diario)
                    .addComponent(fundo30_diario)
                    .addComponent(topoDiario))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fundo30)
                    .addComponent(topoDiario))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topo30)
                    .addComponent(fundo30_diario))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(fundoDiario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topo30_diario)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atributos da ocorrencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ponto");

        sim_ponto.setText("Sim");
        sim_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sim_pontoActionPerformed(evt);
            }
        });

        nao_ponto.setText("Não");
        nao_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nao_pontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sim_ponto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(nao_ponto)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sim_ponto)
                    .addComponent(nao_ponto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Range");

        sim_ranger.setText("4pts");
        sim_ranger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sim_rangerActionPerformed(evt);
            }
        });

        nao_ranger.setText("6pts");
        nao_ranger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nao_rangerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(sim_ranger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nao_ranger)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sim_ranger)
                    .addComponent(nao_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Acertou?");

        sim_acertou.setText("Sim");
        sim_acertou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sim_acertouActionPerformed(evt);
            }
        });

        nao_acertou.setText("Não");
        nao_acertou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nao_acertouActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(sim_acertou)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(nao_acertou)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sim_acertou)
                    .addComponent(nao_acertou))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(statusOCR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(date)
                        .addGap(65, 65, 65)
                        .addComponent(labelHora)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date)
                            .addComponent(labelHora)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastro)
                .addGap(30, 30, 30)
                .addComponent(statusOCR)
                .addGap(282, 282, 282))
        );

        setSize(new java.awt.Dimension(658, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
    *retornando nome de cada variavel do checkbox para gravar no db as ocorrencias!!!
     */
    Function<Boolean, String> decisao = p -> p == true ? "sim" : "nao";
    Function<Boolean, String> rang = r -> r == true ? "4pts" : "6pts";


    private Boolean acertou() {
        if (sim_acertou.isSelected()) {
            return true;
        } else {
            return false;
        }
    }
    
/*
    private Boolean rangers() {
        if (sim_ranger.isSelected()) {
            return true;
        } else {
            return false;
        }
    }
*/
    private Boolean ponto() {
        if (sim_ponto.isSelected()) {
            return true;
        } else {
            return false;
        }
    }
private String valor(){
    if(sim_ranger.isSelected() == true && nao_ranger.isSelected() == false){
        String quatro = "4pts";
        return quatro;
    }else if(sim_ranger.isSelected() == false && nao_ranger.isSelected() == true){
        String seis = "6pts";
        return seis;
    }else{String zero = "0";
        return zero;
    }
}

    /*
    private int horas() {
        if (nove.isSelected()) {
            return 9;
        } else if (dez.isSelected()) {
            return 10;
        } else if (onze.isSelected()) {
            return 11;
        } else if (doze.isSelected()) {
            return 12;
        } else if (treze.isSelected()) {
            return 13;
        } else if (quatorze.isSelected()) {
            return 14;
        } else if (quinze.isSelected()) {
            return 15;
        } else if (dezeseis.isSelected()) {
            return 16;
        } else if (dezesete.isSelected()) {
            return 17;
        } else {
            return 0;
        }
    }
     */
    private Boolean verificacao() {
        if (fundo30.isSelected() == false && topo30.isSelected() == false && fundoDiario.isSelected() == false && topoDiario.isSelected() == false && fundo30_diario.isSelected() == false && topo30_diario.isSelected() == false) {

            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
            statusOCR.setForeground(Color.RED);
            statusOCR.setText("Certifique-se que todos os Campos estão marcados corretamente!!!");

            return false;
        } else if (sim_ponto.isSelected() == false && nao_ponto.isSelected() == false) {

            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
            statusOCR.setForeground(Color.RED);
            statusOCR.setText("Certifique-se que todos os Campos estão marcados corretamente!!!");
            return false;
        
        } else if (sim_acertou.isSelected() == false && nao_acertou.isSelected() == false) {

            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
            statusOCR.setForeground(Color.RED);
            statusOCR.setText("Certifique-se que todos os Campos estão marcados corretamente!!!");
        }/* else if (nove.isSelected() == false && dez.isSelected() == false && onze.isSelected() == false && doze.isSelected() == false && treze.isSelected() == false && quatorze.isSelected() == false && quinze.isSelected() == false && dezeseis.isSelected() == false && dezesete.isSelected() == false) {

            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
            statusOCR.setForeground(Color.RED);
            statusOCR.setText("Certifique-se que todos os Campos estão marcados corretamente!!!");

        }*/ else {
            return true;
        }
        return null;
    }

    private void fundo30_diarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundo30_diarioActionPerformed
        // TODO add your handling code here:
        if (fundo30_diario.isSelected()) {
            topo30.setSelected(false);
            fundo30.setSelected(false);
            fundoDiario.setSelected(false);
            topoDiario.setSelected(false);
            topo30_diario.setSelected(false);
        }
    }//GEN-LAST:event_fundo30_diarioActionPerformed

    private void fundo30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundo30ActionPerformed
        // TODO add your handling code here:
        if (fundo30.isSelected()) {
            topo30.setSelected(false);
            fundo30_diario.setSelected(false);
            fundoDiario.setSelected(false);
            topoDiario.setSelected(false);
            topo30_diario.setSelected(false);
        }
    }//GEN-LAST:event_fundo30ActionPerformed

    private void topo30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topo30ActionPerformed
        // TODO add your handling code here:
        if (topo30.isSelected()) {
            fundo30.setSelected(false);
            fundo30_diario.setSelected(false);
            fundoDiario.setSelected(false);
            topoDiario.setSelected(false);
            topo30_diario.setSelected(false);
        }
    }//GEN-LAST:event_topo30ActionPerformed

    private void fundoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundoDiarioActionPerformed
        // TODO add your handling code here:
        if (fundoDiario.isSelected()) {
            fundo30.setSelected(false);
            topo30.setSelected(false);
            fundo30_diario.setSelected(false);
            topoDiario.setSelected(false);
            topo30_diario.setSelected(false);
        }
    }//GEN-LAST:event_fundoDiarioActionPerformed

    private void topoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topoDiarioActionPerformed
        // TODO add your handling code here:
        if (topoDiario.isSelected()) {
            topo30.setSelected(false);
            fundo30_diario.setSelected(false);
            fundoDiario.setSelected(false);
            fundo30.setSelected(false);
            topo30_diario.setSelected(false);
        }
    }//GEN-LAST:event_topoDiarioActionPerformed

    private void topo30_diarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topo30_diarioActionPerformed
        // TODO add your handling code here:
        if (topo30_diario.isSelected()) {
            topo30.setSelected(false);
            fundo30_diario.setSelected(false);
            fundoDiario.setSelected(false);
            topoDiario.setSelected(false);
            fundo30.setSelected(false);
        }
    }//GEN-LAST:event_topo30_diarioActionPerformed

    private void sim_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sim_pontoActionPerformed
        // TODO add your handling code here:
        if (sim_ponto.isSelected()) {
            nao_ponto.setSelected(false);
        }
    }//GEN-LAST:event_sim_pontoActionPerformed

    private void nao_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nao_pontoActionPerformed
        // TODO add your handling code here:
        if (nao_ponto.isSelected()) {
            sim_ponto.setSelected(false);
        }
    }//GEN-LAST:event_nao_pontoActionPerformed

    private void sim_rangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sim_rangerActionPerformed
        // TODO add your handling code here:
        if (sim_ranger.isSelected()) {
            nao_ranger.setSelected(false);
        }
    }//GEN-LAST:event_sim_rangerActionPerformed

    private void nao_rangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nao_rangerActionPerformed
        // TODO add your handling code here:
        if (nao_ranger.isSelected()) {
            sim_ranger.setSelected(false);
        }
    }//GEN-LAST:event_nao_rangerActionPerformed

    private void sim_acertouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sim_acertouActionPerformed
        // TODO add your handling code here:
        if (sim_acertou.isSelected()) {
            nao_acertou.setSelected(false);
        }
    }//GEN-LAST:event_sim_acertouActionPerformed

    private void nao_acertouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nao_acertouActionPerformed
        // TODO add your handling code here:
        if (nao_acertou.isSelected()) {
            sim_acertou.setSelected(false);
        }
    }//GEN-LAST:event_nao_acertouActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:

        verificacao();
        if (verificacao() == true) {
            System.out.println("chegou aqui");
            ArrayList<Object> lista = new ArrayList<>();
/*
            MongoClient mongoCliente = new MongoClient();

            MongoDatabase database = mongoCliente.getDatabase("dbTraders");

            MongoCollection<Document> collection = database.getCollection("ocorrencias");
*/
            if (fundo30.isSelected() || topo30.isSelected() || fundoDiario.isSelected() || topoDiario.isSelected() || fundo30_diario.isSelected() || topo30_diario.isSelected()) {

                String hr = new CapturandoHora().hora(labelHora.getText());
                int hrs = Integer.valueOf(hr);
                
                if(hrs < 9 || hrs > 17){
                    statusOCR.setText("Horario não permitido para o cadastro da ocorrencia!!!");
                }else{
                  Document doc = new Document("nome", nomes())
                        .append("acertou", decisao.apply(acertou()))
                        .append("ranger", valor())
                        .append("ponto", decisao.apply(ponto()))
                        .append("hora", hrs)
                        .append("data", date.getText());

                collection.insertOne(doc);

                MongoCursor<Document> cursor = collection.find().iterator();

                try {
                    while (cursor.hasNext()) {
                        boolean verificando = cursor.next().equals(doc);
                        System.out.println(verificando);
                        if (verificando == true) {
                            System.out.println(doc);
                            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
                            statusOCR.setForeground(Color.GREEN);
                            statusOCR.setText("Cadastro efetuado com sucesso");
                        }
                    }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e);
                } finally {
                    cursor.close();
                }
   
                }
                
            }
/*
            if (topo30.isSelected()) {
                String hr = new CapturandoHora().hora(labelHora.getText());
                int hrs = Integer.valueOf(hr);
                  if(hrs < 9 || hrs > 17){
                    statusOCR.setText("Horario não permitido para o cadastro da ocorrencia!!!");
                }else{
                  Document doc = new Document("nome", fundoDeTrinta())
                        .append("acertou", decisao.apply(acertou()))
                        .append("ranger", valor())
                        .append("ponto", decisao.apply(ponto()))
                        .append("hora", hrs)
                        .append("data", date.getText());

                collection.insertOne(doc);

                MongoCursor<Document> cursor = collection.find().iterator();

                try {
                    while (cursor.hasNext()) {
                        boolean verificando = cursor.next().equals(doc);
                        System.out.println(verificando);
                        if (verificando == true) {
                            System.out.println(doc);
                            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
                            statusOCR.setForeground(Color.GREEN);
                            statusOCR.setText("Cadastro efetuado com sucesso");
                        }
                    }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e);
                } finally {
                    cursor.close();
                }
   
                }
            }

            if (fundoDiario.isSelected()) {
                String hr = new CapturandoHora().hora(labelHora.getText());
                int hrs = Integer.valueOf(hr);
                 if(hrs < 9 || hrs > 17){
                    statusOCR.setText("Horario não permitido para o cadastro da ocorrencia!!!");
                }else{
                  Document doc = new Document("nome", fundoDeTrinta())
                        .append("acertou", decisao.apply(acertou()))
                        .append("ranger", valor())
                        .append("ponto", decisao.apply(ponto()))
                        .append("hora", hrs)
                        .append("data", date.getText());

                collection.insertOne(doc);

                MongoCursor<Document> cursor = collection.find().iterator();

                try {
                    while (cursor.hasNext()) {
                        boolean verificando = cursor.next().equals(doc);
                        System.out.println(verificando);
                        if (verificando == true) {
                            System.out.println(doc);
                            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
                            statusOCR.setForeground(Color.GREEN);
                            statusOCR.setText("Cadastro efetuado com sucesso");
                        }
                    }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e);
                } finally {
                    cursor.close();
                }
   
                }

            }

            if (topo30_diario.isSelected()) {
                   String hr = new CapturandoHora().hora(labelHora.getText());
                int hrs = Integer.valueOf(hr);
                if(hrs < 9 || hrs > 17){
                    statusOCR.setText("Horario não permitido para o cadastro da ocorrencia!!!");
                }else{
                  Document doc = new Document("nome", fundoDeTrinta())
                        .append("acertou", decisao.apply(acertou()))
                        .append("ranger", valor())
                        .append("ponto", decisao.apply(ponto()))
                        .append("hora", hrs)
                        .append("data", date.getText());

                collection.insertOne(doc);

                MongoCursor<Document> cursor = collection.find().iterator();

                try {
                    while (cursor.hasNext()) {
                        boolean verificando = cursor.next().equals(doc);
                        System.out.println(verificando);
                        if (verificando == true) {
                            System.out.println(doc);
                            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
                            statusOCR.setForeground(Color.GREEN);
                            statusOCR.setText("Cadastro efetuado com sucesso");
                        }
                    }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e);
                } finally {
                    cursor.close();
                }
   
                }
            }

            if (fundo30_diario.isSelected()) {
                   String hr = new CapturandoHora().hora(labelHora.getText());
                int hrs = Integer.valueOf(hr);
                 if(hrs < 9 || hrs > 17){
                    statusOCR.setText("Horario não permitido para o cadastro da ocorrencia!!!");
                }else{
                  Document doc = new Document("nome", fundoDeTrinta())
                        .append("acertou", decisao.apply(acertou()))
                        .append("ranger", valor())
                        .append("ponto", decisao.apply(ponto()))
                        .append("hora", hrs)
                        .append("data", date.getText());

                collection.insertOne(doc);

                MongoCursor<Document> cursor = collection.find().iterator();

                try {
                    while (cursor.hasNext()) {
                        boolean verificando = cursor.next().equals(doc);
                        System.out.println(verificando);
                        if (verificando == true) {
                            System.out.println(doc);
                            statusOCR.setFont(new Font("Sans-serif", Font.BOLD, 14));
                            statusOCR.setForeground(Color.GREEN);
                            statusOCR.setText("Cadastro efetuado com sucesso");
                        }
                    }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e);
                } finally {
                    cursor.close();
                }
   
                }

            }
        }

*/
    }//GEN-LAST:event_cadastroActionPerformed
    }
    private String nomes(){
        String nome;
        if(fundo30.isSelected()){
          nome =  fundo30.getText();
          return nome;
        }else if(topo30.isSelected()){
            nome = topo30.getText();
            return nome;
        }else if(fundoDiario.isSelected()){
            nome = fundoDiario.getText();
            return nome;
        }else if(topoDiario.isSelected()){
            nome = topoDiario.getText();
            return nome;
        }else if(topo30_diario.isSelected()){
            nome = topo30_diario.getText();
            return nome;
        }else if(fundo30_diario.isSelected()){
            nome = fundo30_diario.getText();
            return nome;
        }else{
            statusOCR.setFont(new Font("sans-serif", Font.BOLD, 14));
            statusOCR.setForeground(Color.red);
            statusOCR.setText("Checkbox de nomes não estão marcados corretamente!!!");
            return null;
        }
    }
    private void atualizarHoras() {
        LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formatar = DateTimeFormatter.ofPattern("HH:mm:ss");
        String hora = formatar.format(agora);
        labelHora.setText(hora);
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatter = DateFormat.getDateInstance(DateFormat.SHORT);
        date.setText(formatter.format(data));

        Timer timer = new Timer(1000, event -> {
            atualizarHoras();
        });

        timer.start();

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroOCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroOCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroOCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroOCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOCR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastro;
    private javax.swing.JLabel date;
    private javax.swing.JCheckBox fundo30;
    private javax.swing.JCheckBox fundo30_diario;
    private javax.swing.JCheckBox fundoDiario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelHora;
    private javax.swing.JCheckBox nao_acertou;
    private javax.swing.JCheckBox nao_ponto;
    private javax.swing.JCheckBox nao_ranger;
    private javax.swing.JCheckBox sim_acertou;
    private javax.swing.JCheckBox sim_ponto;
    private javax.swing.JCheckBox sim_ranger;
    private javax.swing.JLabel statusOCR;
    private javax.swing.JCheckBox topo30;
    private javax.swing.JCheckBox topo30_diario;
    private javax.swing.JCheckBox topoDiario;
    // End of variables declaration//GEN-END:variables
}
