/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.traders.app;

import java.awt.Color;
import java.awt.Font;
import java.text.DateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author Windows 7
 */
public class MainPage extends javax.swing.JFrame {

    CadastroOCR automatico = new CadastroOCR();
     Estatisticas frame = new Estatisticas();
     CadastroOCRManual manual = new CadastroOCRManual();
     Sobre sobre = new Sobre();
    
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JLabel();
        ola = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        cadastro = new javax.swing.JMenuItem();
        cadastroManual = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        estatistica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        sobreText = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Começo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBar1.setRollover(true);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        data.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(ola)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(data)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(data)
                .addGap(59, 59, 59)
                .addComponent(ola)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jMenu3.setText("Cadastro");

        cadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        cadastro.setText("Cadastro autômatico");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });
        jMenu3.add(cadastro);

        cadastroManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        cadastroManual.setText("Cadastro Manual");
        cadastroManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroManualActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroManual);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Estatistica");

        estatistica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        estatistica.setText("Estatistica");
        estatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatisticaActionPerformed(evt);
            }
        });
        jMenu4.add(estatistica);

        jMenuBar2.add(jMenu4);

        jMenu2.setText("Sobre");

        sobreText.setText("Sobre");
        sobreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreTextActionPerformed(evt);
            }
        });
        jMenu2.add(sobreText);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(560, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:
        
        if(automatico.isVisible() == true){
            
        }else{
            
        automatico.setVisible(true);
        }
    }//GEN-LAST:event_cadastroActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        int horas = 0;
        Date date = new Date();
        DateFormat formatter = DateFormat.getDateInstance(DateFormat.SHORT);
        String dataText = formatter.format(date);
        data.setText(dataText);
        
        
         LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formatar = DateTimeFormatter.ofPattern("HH");
        String hora = formatar.format(agora);
        
        horas = Integer.valueOf(hora);
        
        if(horas >= 6 && horas < 12){
           ola.setForeground(Color.blue);
            ola.setFont(new Font("sans-serif", Font.BOLD, 16));
            ola.setText("Bom dia, Eduardo!!!");
        }else if( horas >= 12 && horas < 18){
               ola.setForeground(Color.blue);
            ola.setFont(new Font("sans-serif", Font.BOLD, 16));
            ola.setText("Boa tarde, Eduardo!!!");
        }else if(horas >= 18 && horas < 24){
                ola.setForeground(Color.blue);
            ola.setFont(new Font("sans-serif", Font.BOLD, 16));
            ola.setText("Boa noite, Eduardo!!!");
        }else{
            System.out.println("erro...");
        }
            
        
    }//GEN-LAST:event_formWindowActivated

    private void estatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatisticaActionPerformed
        // TODO add your handling code here:
       
        if(frame.isVisible() == true){
            
        }else{
            
        frame.setVisible(true);
        }
        
    }//GEN-LAST:event_estatisticaActionPerformed

    private void cadastroManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroManualActionPerformed
        // TODO add your handling code here:
        if(manual.isVisible() == true){
            
        }else{
            manual.setVisible(true);
        }
    }//GEN-LAST:event_cadastroManualActionPerformed

    private void sobreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreTextActionPerformed
        // TODO add your handling code here:
        if(sobre.isVisible() == true){
            
        }else{
            sobre.setVisible(true);
        }
    }//GEN-LAST:event_sobreTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastro;
    private javax.swing.JMenuItem cadastroManual;
    public static javax.swing.JLabel data;
    private javax.swing.JMenuItem estatistica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel ola;
    private javax.swing.JMenuItem sobreText;
    // End of variables declaration//GEN-END:variables
}
